name: Terraform Destroy Workflow

on:
  workflow_dispatch: # Allows manual triggering of this workflow

jobs:
  terraform-destroy:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your AWS region

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7 # Replace with your Terraform version

    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init

    - name: Destroy Terraform Infrastructure
      working-directory: ./terraform
      run: terraform destroy -auto-approve
